backend:
  name: auth0
  auth0_domain: "dev-ourgvx80wfgifw08.eu.auth0.com"
  auth0_client_id: "qDKwTb7eCqxHnaWNMkWBEz7hw5PQmrKz"
  auth0_callback_url: "https://religion-unterrichten.onrender.com/admin/"
  branch: main

media_folder: "bilder/uploads"
public_folder: "/bilder/uploads"

collections:
  - name: "seiten"
    label: "Seiten"
    files:
      - file: "index.html"
        label: "Startseite"
        name: "start"
        fields:
          - { label: "Titel", name: "title", widget: "string" }
          - { label: "Inhalt", name: "body", widget: "markdown" }

      - file: "materialien.html"
        label: "Materialien"
        name: "materialien"
        fields:
          - { label: "Titel", name: "title", widget: "string" }
          - { label: "Inhalt", name: "body", widget: "markdown" }

      - file: "ideen.html"
        label: "Ideen"
        name: "ideen"
        fields:
          - { label: "Titel", name: "title", widget: "string" }
          - { label: "Inhalt", name: "body", widget: "markdown" }
