backend:
  name: git-gateway
  branch: main

media_folder: "bilder/uploads"
public_folder: "/bilder/uploads"

collections:
  - name: "seiten"
    label: "Seiten"
    files:
      - file: "index.html"
        label: "Startseite"
        name: "index"
        fields:
          - {label: "Titel", name: "title", widget: "string"}
          - {label: "Inhalt", name: "body", widget: "markdown"}
      - file: "materialien.html"
        label: "Materialien"
        name: "materialien"
        fields:
          - {label: "Titel", name: "title", widget: "string"}
          - {label: "Inhalt", name: "body", widget: "markdown"}
      - file: "ideen.html"
        label: "Ideen"
        name: "ideen"
        fields:
          - {label: "Titel", name: "title", widget: "string"}
          - {label: "Inhalt", name: "body", widget: "markdown"}
      - file: "kontakt.html"
        label: "Kontakt"
        name: "kontakt"
        fields:
          - {label: "Titel", name: "title", widget: "string"}
          - {label: "Inhalt", name: "body", widget: "markdown"}
